# Generated by Django 6.0.1 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenapi",
            name="bank_details",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="kitchenapi",
            name="gallery_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="kitchenapi",
            name="notification_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kitchenapi",
            name="operating_hours",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
